version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: quest
      RABBITMQ_DEFAULT_PASS: quest
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 15s
      retries: 1

  audit:
    build:
      context: ./audit
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8380:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: quest
      SPRING_RABBITMQ_PASSWORD: quest

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8280:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: quest
      SPRING_RABBITMQ_PASSWORD: quest

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8180:8080"
    environment:
      PRODUCING: true
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: quest
      SPRING_RABBITMQ_PASSWORD: quest
